blank_issues_enabled: false
contact_links:
  - name: General Questions
    url: https://github.com/dannyboy2323/awtb/discussions
    about: For questions that are not bugs or feature requests, use Discussions.
